channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - pip=20.1
  - pip:
      - rpaframework==10.0.6
      - selenium==4.0.0
      - XlsxWriter==3.0.1
      - pandas==1.3.4
      - PyMuPDF==1.19.1
      - PyPDF2
